### ISSUE TITLE
Downloading is not implemented, issues that may come up because of redirects

### ISSUE THREAD

**Issue by Dioarya** [chirag-droid/anime-cli#10]
I tried downloading the anime using vlc, the url redirected to another url with a different part of the video.

example of the url redirects : 
https://.../{id}.m3u8
https://.../{id}.3600.ts
https://.../{id}.3601.ts
https://.../{id}.3602.ts
https://.../{id}.3603.ts

and because of the redirects, vlc thought the downloading process was over and in turn it only downloaded ~4 seconds before each redirect. 

I think this should be considered when implementing downloading that gogoanime makes it hard to download the whole file right away because of redirects, and I also want to bump the anime downloading implementation progress.

By the way the anime and episode is Naruto and episode 1 and not from browser.

**Comment by chirag-droid** [comment]
This project is going to be archived. use this now if you want to [chirag-droid/animeflix](https://github.com/chirag-droid/animeflix)
