### ISSUE TITLE
script crashes after search query is submitted

### ISSUE THREAD

**Issue by J-Reis** [chirag-droid/anime-cli#5]
Attempting to use anime-cli via Termux on an SGS9. I'm far from being either a termux or a python wizard, so the issue may not actually be with anime-cli, but I'm not quite savvy enough to determine that for myself, so please forgive me!

anime-cli appears to install normally via `pip install anime-cli`

When I start the script by entering `anime-cli` I'm greeted with the prompt `? What anime would you like to watch?`. Regardless of what I enter, the result is a stream of errors ending with: `InquirerPy.exceptions.InvalidArgument: argument choices cannot be empty`

Python version is 3.10.0
Please let me know if there are any logs I can share or further information I can provide.
<details>
<summary>Termux Screenshot:</summary>
<img src=https://user-images.githubusercontent.com/23666144/140672223-9334ec8f-022f-420c-80c1-b3bf026f4fe9.jpg></details>

**Comment by chirag-droid** [comment]
Thanks, for reporting the issue, seems like gogoanime moved to some other site which is causing the issue

**Comment by chirag-droid** [comment]
Hey, I have fixed this issue, update anime-cli by running
```
pip install anime-cli --upgrade
```
although streaming to video player is still broken and I am working on it

**Comment by chirag-droid** [comment]
Update, I have fixed the issue completely. I am closing this now, you can open it anytime again
just upgrade the anime-cli version
